
- hosts: all
  user: cloud
  become: true
  roles:
     - { role: common }
     - { role: apache, when: Application_type == "php" }
     - { role: php, when: Application_type == "php" }
     - { role: tomcat, when: Application_type == "tomcat" }
     - { role: nodejs, when: Application_type == "nodejs" }

  tasks:
     - name: mount
       mount:
        name: "{{ app_directory }}"
        src: "{{ gluster_ip }}:/gluster"
        fstype: nfs
        state: mounted
       ignore_errors: yes


     - name: cron mount
       cron: name="check dirs" job=" sleep 30 ; mount -a"


