---
- hosts: all
  user: cloud
  become: true
  roles:
    - nodejs
  tasks:

    - name: deploy node
      shell: git clone {{ Application_source }} /nodejs
      when: gluster_ip  == '10.0.0.120'
    - name: launch app
      shell: sudo node /nodejs/app.js > /tmp/output.log &

