---
- hosts: all
  user: cloud
  become: true
  roles:
    - apache
    - php
  tasks:

    - name: deploy php
      shell: git clone {{ Application_source }} /var/www/html/tmp && mv /var/www/html/tmp/* /var/www/html/ && rm -rf /var/www/html/tmp && rm -rf /var/www/html/index.html
      when: gluster_ip  == '10.0.0.120'