---
- hosts: all
  user: cloud
  become: true
  pre_tasks:

  roles:
    - common
  tasks:

   - name: create Application
     file: path={{ app_directory }} state=directory recurse=yes mode=0755

   - name: Check gluster will be up
     wait_for: host={{ gluster_ip }} port=24007

   - name: mount
     mount:
      name: "{{ app_directory }}"
      src: "{{ gluster_ip }}:/gluster"
      fstype: glusterfs
      opts: "defaults,_netdev"
      state: mounted

   - name: shell mount
     shell: |
             wait 20
             mount -a
