---
- hosts: all
  user: cloud
  become: true
  pre_tasks:

  roles:
    - common
  tasks:

   - name: create Application
     file: path={{ app_directory }} state=directory recurse=yes mode=0755

   - name : wait gluster is up
     action: shell nc -vz {{ gluster_ip }} 24007
     register: result
     until: result.stdout.find("succeeded") != -1 or result.stdout.find("open") != -1
     retries: 60
     delay: 2

   - name: mount
     mount:
      name: "{{ app_directory }}"
      src: "{{ gluster_ip }}:/gluster"
      fstype: glusterfs
      opts: "defaults,_netdev"
      state: mounted

