---
- hosts: all
  user: cloud
  become: true
  pre_tasks:

  roles:
    - common
  tasks:

   - name: Wait until glsuterds is available
     local_action:
       module: wait_for
       host: "{{ gluster_ip }}"
       port: 24007
       delay: 60
       timeout: 320
       state: started


   - name: create Application
     file: path={{ app_directory }} state=directory recurse=yes mode=0755

   - name: mount
     mount:
      name: "{{ app_directory }}"
      src: "{{ gluster_ip }}:/gluster"
      fstype: glusterfs
      opts: "defaults,_netdev"
      state: mounted

