heat_template_version: 2013-05-23

parameters:
  network:
    label: network
    type: string
  subnet:
    label: subnet
    type: string
  os_type:
    label: os type
    type: string
  nodename:
    label: nodename
    type: string
  index:
    label: index
    type: string
  nodeip:
    label: nodeip
    type: string
  security_group:
    label: security_group
    type: string
  keypair_name:
    label: SSH Keypair
    type: string
  pool_id:
    label: pool id
    type: string
  flavor_name:
    default: n2.cw.standard-1
    type: string
    label: Instance Type (Flavor)
    constraints:
      - allowed_values:
          - s1.cw.small-1
          - n2.cw.standard-1
          - n2.cw.standard-2
          - n1.cw.standard-4
          - n1.cw.standard-8
          - n1.cw.standard-12
          - n1.cw.standard-16
          - n1.cw.highmem-4
  clusters_size:
    label: number of nodes
    type: number
  db_name:
    label: database name
    type: string
  db_admin:
    label: database admin
    type: string
  db_admin_password:
    label: database admin password
    type: string


resources:
  db_port:
      type: OS::Neutron::Port
      properties:
        network: { get_param: network }
        fixed_ips:
          - ip_address: { get_param: nodeip }
            subnet_id: { get_param: subnet }
        security_groups:
          - { get_param: security_group }

  node:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: { get_param: os_type }
      flavor: { get_param: flavor_name }
      user_data_format: RAW
      networks:
       - port: { get_resource: db_port }
      name: {get_param: nodename}
      user_data:
        str_replace:
          template: |
             #!/bin/bash
             mkdir /etc/ansible
             echo "[local]" >> /etc/ansible/hosts
             echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
                cat << EOF > /etc/ansible/vars.yml
                 ip_node: 10.0.1.1$index
                 hostname: node$index
                 db_name: $db_name
                 db_admin: $db_admin
                 db_admin_password: $db_admin_password
                 master_ip: 10.0.1.10
                 #on pv_disk you can use many disks juste add , exemple /dev/vdb , /dev/vdc
                 pv_disk: /dev/vdb
                 vg_name: vg0
                 lv_name: global
                 lv_size : 8g
             EOF

               if [ $index -eq 0 ]
               then
               echo "    master: true" >> /etc/ansible/vars.yml
               else
               echo "    master: false" >> /etc/ansible/vars.yml
               fi
               START=1
               END=$clusters_size
               echo "10.0.1.10 node0" >> /etc/hosts
               TEMP="clusters: 10.0.1.10"
               for ((i=1;i<$END;i++)); do
               echo "10.0.1.1$i node$i" >> /etc/hosts
               TEMP=$TEMP,10.0.1.1$i
               done
               echo "    $TEMP" >> /etc/ansible/vars.yml
               if [ "$os" == "Debian Jessie" ] ;
               then
               /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git db.yml -e @/etc/ansible/vars.yml
               else
               ansible-pull -U https://github.com/dalitun/ansible-playbook.git db.yml -e @/etc/ansible/vars.yml
               fi

          params:

            $index: { get_param: index }
            $db_name: { get_param: db_name}
            $db_admin: { get_param: db_admin }
            $db_admin_password: { get_param: db_admin_password }
            $os: { get_param: os_type }
            $clusters_size: { get_param: clusters_size }
  Data:
     type: OS::Cinder::Volume
     properties:
       size: 10

  Data_att:
     type: OS::Cinder::VolumeAttachment
     properties:
       instance_uuid: { get_resource: node }
       volume_id: { get_resource: Data }
       mountpoint: /dev/vdb


  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [node , first_address]}
      protocol_port: 3306
