heat_template_version: 2013-05-23

parameters:
  network:
    label: network
    type: string
  subnet:
    label: subnet
    type: string
  os_type:
    description: os type
    label: os type
    type: string
  security_group:
    label: security_group
    type: string
  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string
  db_type:
    description: database type
    label: database type
    type: string
  db_name:
    description: database name
    label: database name
    type: string
  db_admin:
    description: database name
    label: database admin
    type: string
  db_admin_password:
    description: database admin password
    label: database admin password
    type: string

  flavor_name:
    default: n2.cw.standard-1
    description: Flavor to use for the deployed instance
    type: string
    label: Instance Type (Flavor)
    constraints:
      - allowed_values:
          - s1.cw.small-1
          - n2.cw.standard-1
          - n2.cw.standard-2
          - n1.cw.standard-4
          - n1.cw.standard-8
          - n1.cw.standard-12
          - n1.cw.standard-16
          - n1.cw.highmem-4
resources:

  vip_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network  }
      fixed_ips:
        - ip_address: 10.0.1.10
          subnet_id: { get_param: subnet }
      security_groups: [{ get_param: security_group }]



  db_port1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network }
      allowed_address_pairs:
        - ip_address: 10.0.1.10
      fixed_ips:
        - ip_address: 10.0.1.2
          subnet_id: { get_param: subnet }
      security_groups: [{ get_param: security_group }]

  db_port2:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network }
      allowed_address_pairs:
        - ip_address: 10.0.1.10
      fixed_ips:
        - ip_address: 10.0.1.3
          subnet_id: { get_param: subnet }
      security_groups: [{ get_param: security_group }]


  master1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      name:
        str_replace:
           template: $stack-db1
           params:
              $stack: { get_param: 'OS::stack_name' }
      image: { get_param: os_type }
      flavor: { get_param: flavor_name }
      networks:
        - port: { get_resource: db_port1 }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
                  #!/bin/bash
                  mkdir /etc/ansible
                  echo "[local]" >> /etc/ansible/hosts
                  echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
                  cat << EOF > /etc/ansible/vars.yml
                   database_type: $db_type
                   server_id: 1
                   db_name: $db_name
                   db_admin: $db_admin
                   db_admin_password: $db_admin_password
                   master_ip: 10.0.1.3
                   #on pv_disk you can use many disks juste add , exemple /dev/vdb , /dev/vdc
                   pv_disk: /dev/vdb
                   vg_name: vg0
                   lv_name: global
                   lv_size : 8g
                  EOF
                   if [ "$os" == "Debian Jessie" ]
                  then
                  /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git db.yml -e @/etc/ansible/vars.yml
                  else
                  ansible-pull -U https://github.com/dalitun/ansible-playbook.git db.yml -e @/etc/ansible/vars.yml
                  fi
          params:
                $db_type: { get_param: db_type }
                $db_name: { get_param: db_name}
                $db_admin: { get_param: db_admin }
                $db_admin_password: { get_param: db_admin_password }
                $os: { get_param: os_type }

  master2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: { get_param: os_type }
      name:
        str_replace:
           template: $stack-db2
           params:
              $stack: { get_param: 'OS::stack_name' }
      flavor: { get_param: flavor_name }
      networks:
        - port: { get_resource: db_port2 }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
                  #!/bin/bash
                  mkdir /etc/ansible
                  echo "[local]" >> /etc/ansible/hosts
                  echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
                  cat << EOF > /etc/ansible/vars.yml
                   database_type: $db_type
                   server_id: 2
                   db_name: $db_name
                   db_admin: $db_admin
                   db_admin_password: $db_admin_password
                   master_ip: 10.0.1.2
                   #on pv_disk you can use many disks juste add , exemple /dev/vdb , /dev/vdc
                   pv_disk: /dev/vdb
                   vg_name: vg0
                   lv_name: global
                   lv_size : 8g
                  EOF

                   if [ "$os" == "Debian Jessie" ]
                  then
                  /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git db.yml -e @/etc/ansible/vars.yml
                  else
                  ansible-pull -U https://github.com/dalitun/ansible-playbook.git db.yml -e @/etc/ansible/vars.yml
                  fi



          params:
                $db_type: { get_param: db_type }
                $db_name: { get_param: db_name}
                $db_admin: { get_param: db_admin }
                $db_admin_password: { get_param: db_admin_password }
                $os: { get_param: os_type }


  Data1:
    type: OS::Cinder::Volume
    properties:
      size: 10

  Data1_att:
     type: OS::Cinder::VolumeAttachment
     properties:
       instance_uuid: { get_resource: master1 }
       volume_id: { get_resource: Data1 }
       mountpoint: /dev/vdb


  Data2:
    type: OS::Cinder::Volume
    properties:
      size: 10

  Data2_att:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: master2 }
      volume_id: { get_resource: Data2 }
      mountpoint: /dev/vdb
