heat_template_version: 2013-05-23
parameters:
  network:
    label: network
    type: string
  subnet:
    label: subnet
    type: string
  os_type:
    description: os type
    label: os type
    type: string
  nodename:
    label: nodename
    type: string
  index:
    label: index
    type: string
  nodeip:
    label: nodeip
    type: string
  number_glusterfs:
    label: number of nodes
    type: number
  security_group:
    label: security_group
    type: string
  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string
  flavor_name:
    type: string
    label: Instance Type (Flavor)
  Application_type:
    label: Application_type
    type: string
  Application_source:
    label: Application_source
    type: string

resources:

  glusterfs_port:
      type: OS::Neutron::Port
      properties:
        network: { get_param: network }
        fixed_ips:
          - ip_address: { get_param: nodeip }
            subnet_id: { get_param: subnet }
        security_groups:
          - { get_param: security_group }

  node:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      name: {get_param: nodename }
      image: { get_param: os_type }
      flavor: { get_param: flavor_name }
      networks:
        - port: { get_resource: glusterfs_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
                  #!/bin/bash
                  mkdir /etc/ansible
                  echo "[local]" >> /etc/ansible/hosts
                  echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
                   cat << EOF > /etc/ansible/vars.yml
                   gluster_mount_dir: /mnt/gluster
                   gluster_brick_dir: /srv/gluster/brick
                   gluster_brick_name: gluster
                   Application_type: $Application_type
                   Application_source: $Application_source
                   node:
                  EOF
                    END=$number_glusterfs
                    for ((i=0;i<$END;i++)); do
                    echo "   $i:  10.0.1.12$i" >> /etc/ansible/vars.yml
                    done


                  if [ "$os" == "Debian Jessie" ] ;
                  then
                  /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git glusterfs.yml -e @/etc/ansible/vars.yml
                  else
                  ansible-pull -U https://github.com/dalitun/ansible-playbook.git glusterfs.yml -e @/etc/ansible/vars.yml
                  fi
          params:
                $os: { get_param: os_type }
                $Application_type: { get_param: Application_type }
                $Application_source: { get_param: Application_source }
                $number_glusterfs: { get_param: number_glusterfs }