heat_template_version: 2013-05-23

parameters:
  network:
    label: network
    type: string
  subnet:
    label: subnet
    type: string
  os_type:
    label: os type
    type: string
  nodename:
    label: nodename
    type: string
  index:
    label: index
    type: string

  Application_type:
    label: Application_type
    type: string
  Application_source:
    label: Application_source
    type: string
  security_group:
    label: security_group
    type: string
  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string
  pool_id:
     description: pool id
     label: pool id
     type: string
  flavor_name:
    default: n2.cw.standard-1
    description: Flavor to use for the deployed instance
    type: string
    label: Instance Type (Flavor)
    constraints:
      - allowed_values:
          - s1.cw.small-1
          - n2.cw.standard-1
          - n2.cw.standard-2
          - n1.cw.standard-4
          - n1.cw.standard-8
          - n1.cw.standard-12
          - n1.cw.standard-16
          - n1.cw.highmem-4

resources:
  web_port:
      type: OS::Neutron::Port
      properties:
        network: { get_param: network }
        security_groups:
          - { get_param: security_group }
  node:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: { get_param: os_type }
      flavor: { get_param: flavor_name }
      user_data_format: RAW
      networks:
       - port: { get_resource: web_port }
      name: {get_param: nodename}
      user_data:
        str_replace:
          template: |
             #!/bin/bash
             sleep 20
             mkdir /etc/ansible
             echo "[local]" >> /etc/ansible/hosts
             echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
              rem=$(( $index % 2 ))
              if [ $rem -eq 0 ]
              then
                cat << EOF > /etc/ansible/vars.yml
                 Application_source: $Application_source
                 gluster_ip: 10.0.0.120
             EOF
              else
                cat << EOF > /etc/ansible/vars.yml
                 Application_source: $Application_source
                 gluster_ip: 10.0.0.130
             EOF
              fi

              case "$Application_type" in

              "php5")
                      echo "    app_directory: /var/www/html" >> /etc/ansible/vars.yml

                      if [ "$os" == "Debian Jessie"] ;
                       then
                       /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git pre-setup.yml -e @/etc/ansible/vars.yml

                       /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git php.yml -e @/etc/ansible/vars.yml
                       else

                       ansible-pull -U https://github.com/dalitun/ansible-playbook.git pre-setup.yml -e @/etc/ansible/vars.yml

                       ansible-pull -U https://github.com/dalitun/ansible-playbook.git php.yml -e @/etc/ansible/vars.yml

                        fi
                                     ;;
              "tomcat")
                        echo "    app_directory: /opt/tomcat" >> /etc/ansible/vars.yml

                        if [ "$os" == "Debian Jessie" ] ;
                        then
                        /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git pre-setup.yml -e @/etc/ansible/vars.yml

                        /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git tomcat.yml -e @/etc/ansible/vars.yml
                        else

                        ansible-pull -U https://github.com/dalitun/ansible-playbook.git pre-setup.yml -e @/etc/ansible/vars.yml

                        ansible-pull -U https://github.com/dalitun/ansible-playbook.git tomcat.yml -e @/etc/ansible/vars.yml
                        fi
                                      ;;
              "nodejs") echo "    app_directory: /nodejs" >> /etc/ansible/vars.yml

                        if [ "$os" == "Debian Jessie" ] ;
                        then
                         /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git pre-setup.yml -e @/etc/ansible/vars.yml

                         /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git nodejs.yml -e @/etc/ansible/vars.yml
                         else
                          ansible-pull -U https://github.com/dalitun/ansible-playbook.git pre-setup.yml -e @/etc/ansible/vars.yml

                          ansible-pull -U https://github.com/dalitun/ansible-playbook.git nodejs.yml -e @/etc/ansible/vars.yml

                        fi
                                    ;;
                *) echo "what do you do fuck"
                                     ;;
               esac

          params:

            $index: { get_param: index }
            $Application_type: { get_param: Application_type }
            $Application_source: { get_param: Application_source }
            $os: { get_param: os_type }

  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [node , first_address]}
      protocol_port: 80