heat_template_version: 2013-05-23
parameters:
  network:
    label: network
    type: string
  subnet:
    label: subnet
    type: string
  os_type:
    description: os type
    label: os type
    type: string
  security_group:
    label: security_group
    type: string
  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string
  flavor_name:
    type: string
    label: Instance Type (Flavor)

resources:

  gluster_port1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network  }
      fixed_ips:
        - ip_address: 10.0.0.120
          subnet_id: { get_param: subnet }
      security_groups: [{ get_param: security_group }]

  gluster_port2:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network }
      fixed_ips:
        - ip_address: 10.0.0.130
          subnet_id: { get_param: subnet }
      security_groups: [{ get_param: security_group }]


  gluster1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      name:
         str_replace:
           template: $stack-gluster1
           params:
              $stack: { get_param: 'OS::stack_name' }
      image: { get_param: os_type }
      flavor: { get_param: flavor_name }
      networks:
        - port: { get_resource: gluster_port1 }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
                  #!/bin/bash
                  mkdir /etc/ansible
                  echo "[local]" >> /etc/ansible/hosts
                  echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
                   cat << EOF > /etc/ansible/vars.yml
                   gluster_mount_dir: /mnt/gluster
                   gluster_brick_dir: /srv/gluster/brick
                   gluster_brick_name: gluster
                   node:
                     1: 10.0.0.120
                     2: 10.0.0.130
                  EOF
                  if [ "$os" == "Debian Jessie" ] ;
                  then
                  /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git glusterfs.yml -e @/etc/ansible/vars.yml
                  else
                  ansible-pull -U https://github.com/dalitun/ansible-playbook.git glusterfs.yml -e @/etc/ansible/vars.yml
                  fi
          params:
                $os: { get_param: os_type }

  gluster2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: { get_param: os_type }
      name:
         str_replace:
           template: $stack-gluster2
           params:
              $stack: { get_param: 'OS::stack_name' }
      flavor: { get_param: flavor_name }
      networks:
        - port: { get_resource: gluster_port2 }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
                  #!/bin/bash
                  mkdir /etc/ansible
                  echo "[local]" >> /etc/ansible/hosts
                  echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
                  cat << EOF > /etc/ansible/vars.yml
                   gluster_mount_dir: /mnt/gluster
                   gluster_brick_dir: /srv/gluster/brick
                   gluster_brick_name: gluster
                   node:
                     1: 10.0.0.120
                     2: 10.0.0.130
                  EOF
                  if [ "$os" == "Debian Jessie" ] ;
                  then
                  /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git glusterfs.yml -e @/etc/ansible/vars.yml
                  else
                  ansible-pull -U https://github.com/dalitun/ansible-playbook.git glusterfs.yml -e @/etc/ansible/vars.yml
                  fi
          params:
                $os: { get_param: os_type }