heat_template_version: 2013-05-23

parameters:
  network:
    label: network
    type: string
  subnet:
    label: subnet
    type: string
  os_type:
    label: os type
    type: string
  nodename:
    label: nodename
    type: string
  index:
    label: index
    type: string
  nodeip:
    label: nodeip
    type: string
  Application_type:
    label: Application_type
    type: string
  security_group:
    label: security_group
    type: string
  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string
  pool_id:
     description: pool id
     label: pool id
     type: string
  flavor_name:
    type: string
    label: Instance Type (Flavor)


resources:
  web_port:
      type: OS::Neutron::Port
      properties:
        network: { get_param: network }
        fixed_ips:
          - ip_address: { get_param: nodeip }
            subnet_id: { get_param: subnet }
        security_groups:
          - { get_param: security_group }

  node:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: { get_param: os_type }
      flavor: { get_param: flavor_name }
      user_data_format: RAW
      networks:
       - port: { get_resource: web_port }
      name: {get_param: nodename}
      user_data:
        str_replace:
          template: |
             #!/bin/bash
             mkdir /etc/ansible
             echo "[local]" >> /etc/ansible/hosts
             echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
                cat << EOF > /etc/ansible/vars.yml
                 Application_type: $Application_type
                 gluster_ip: 10.0.0.12$index
              EOF
              case "$Application_type" in

              "php5")
                      echo "    app_directory: /var/www/html" >> /etc/ansible/vars.yml

                      if [ "$os" == "Debian Jessie" ] ;
                       then
                       /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git deploy_nodes.yml -e @/etc/ansible/vars.yml
                       else
                       ansible-pull -U https://github.com/dalitun/ansible-playbook.git deploy_nodes.yml -e @/etc/ansible/vars.yml

                        fi
                                     ;;
              "tomcat")
                        echo "    app_directory: /opt/tomcat/webapps" >> /etc/ansible/vars.yml
                        if [ "$os" == "Debian Jessie" ] ;
                        then
                        /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git deploy_nodes.yml -e @/etc/ansible/vars.yml
                        else
                        ansible-pull -U https://github.com/dalitun/ansible-playbook.git deploy_nodes.yml -e @/etc/ansible/vars.yml
                        fi
                                      ;;
              "nodejs") echo "    app_directory: /nodejs" >> /etc/ansible/vars.yml
                        if [ "$os" == "Debian Jessie" ] ;
                        then
                         /usr/local/bin/ansible-pull -U https://github.com/dalitun/ansible-playbook.git deploy_nodes.yml -e @/etc/ansible/vars.yml
                         else
                          ansible-pull -U https://github.com/dalitun/ansible-playbook.git deploy_nodes.yml -e @/etc/ansible/vars.yml

                        fi
                                    ;;
                *) echo "what do you do fuck"
                                     ;;
               esac

          params:

            $index: { get_param: index }
            $Application_type: { get_param: Application_type }
            $os: { get_param: os_type }

  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [node , first_address]}
      protocol_port: 80
